#            _  _  _                _   
#  ___ __ _ (_)| || |__  ___  __ _ | |_ 
# (_-</ _` || || || '_ \/ _ \/ _` ||  _|
# /__/\__,_||_||_||_.__/\___/\__,_| \__|
                                      
# Basic Setup:
name = "py39_test"
short_name = "py39"
email = "-"
author = "fecub"
short_description = "-"
description = "long description"
url = "-"
keywords = "py"
license = "none"


# Resource Setup:
[resources]
icon = ""
data_files = [ "*",]
modules = []
file = "app.py"


# Plugin Commands:


# Build Routines:
[build.pyinstaller]
type = 1
mac = true
windows = true
unix = true
bundle_id = "com.fecub.py39"


# Release Routines:


# Other:
[git]
github = "fecub/py39_test"


# Thank you for using Sailboat!